// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace RatingService.Dal.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
	public sealed partial class InitialCreate : IMigrationMetadata
	{
		private readonly ResourceManager Resources = new ResourceManager(typeof(InitialCreate));

		string IMigrationMetadata.Id
		{
			get { return "201605251841102_InitialCreate"; }
		}

		string IMigrationMetadata.Source
		{
			get { return null; }
		}

		string IMigrationMetadata.Target
		{
			get { return Resources.GetString("Target"); }
		}
	}
}
